from questions import *

question_list = []

subject_slug = "12mat2013"

question_list.append(Questions("1.", "", "maths1301q", 0, 0, 0, 0, "[0, ∞] and (0, ∞) ", "R and [0, ∞) ", "[0, ∞) and [0, ∞) ", "[0, ∞) and R", "", "c", "maths1301e", 1, True));
question_list.append(Questions("2.", "Which one of the following defines a one-to-one function? \n", 0, 0, 0, 0, "maths1302d", "f= {(x,y): y = 3x-1)} ", "f= {(x,y): x is a sister of y} ", "f= {(x,y): y is a father of x}", "", "", "a", "maths1302e", 1, True));
question_list.append(Questions("3.", "", "maths1303q", 0, 0, 0, 0, "(3, 2) and 3 ", "(3, -2) and 3 ", "(3, 2) and 9 ", "(3, -2) and 9", "", "b", "maths1303e", 1, True));
question_list.append(Questions("4.", "Which one of the following sentences has a truth value? \n", 0, 0, 0, 0, 0, "We shall win! ", "Man is selfish. ", "Tomorrow is a beautiful day. ", "Man is mortal.", "Truth value is a value indicating either true or false, but not both. \nThe statement, man is mortal is true. ", "d", 0, 1, True));
question_list.append(Questions("5.", "", "maths1305q", 0, 0, 0, 0, "-47 ", "-37 ", "37 ", "47", "", "d", "maths1305e", 1, True));
question_list.append(Questions("6.", "The additive inverse of the complex number 3-4i is \n", 0, 0, 0, 0, 0, "-3 – 4i", "3 + 4i ", "-3 - 4i", "3 - 4i", "Additive inverse is a number or set of numbers that when added give zero. For value a + b, its additive inverse is -a -b. \nUsing the above fact \nThe additive inverse of 3 — 4i is-3 + 4i ", "c", 0, 1, True));
question_list.append(Questions("7.", "What is the modulus of the complex number -6 + 8i?\n", 0, 0, 0, 0, 0, 2, "5", "8", "10", "", "d", "maths1307e", 1, True));
question_list.append(Questions("8.", "What are the modulus and argument of the complex number 2 + 2i respectively?\n", 0, 0, 0, 0, 0, "2 and π/4 ", "2√2 and π/4 ", "4 and π/4 ", "2√2 and - π /4", "", "b", "maths1308e", 1, True));
question_list.append(Questions("9.", "Given two vectors u = (1, 3) and v = (-3, 5) in the plane. \nThen 6u + 2v is equal to \n", 0, 0, 0, 0, 0, "(3, 3)", "(0, 18) ", "(0, 28) ", "(2, 28)", "", "c", "maths1309e", 1, True));
question_list.append(Questions("10.", "Which one of the following is the standard form of the equation of the circle centered at (2, -3) and radius 5? \n", 0, "maths1310a", "maths1310b", "maths1310c", "maths1310d", "", "", "", "", "", "a", "maths1310e", 1, True));
question_list.append(Questions("11.", "If f is a continuous function on [a, b] and F is its Anti-derivative, then which of the following is True?\n", 0, "maths1311a", "maths1311b", "maths1311c", "maths1311d", "", "", "", "", "", "d", "maths1311e", 1, True));
question_list.append(Questions("12.", "Which of the following defines the equation of a sphere whose center is at (0, -1, 2) and radius 6 units?\n", 0, "maths1312a", "maths1312b", "maths1312c", "maths1312d", "", "", "", "", "", "b", "maths1312e", 1, True));
question_list.append(Questions("13.", "Which of the following represents the vector (3,-5,7) in the space using the standard unit vectors l, I and k? \n", 0, 0, 0, 0, 0, "3i + 5j + 7k ", "3i – 5j – 7k", "-3i – 5j - 7k ", "3i - 5j + 7k", "", "d", "maths1313e", 1, True));
question_list.append(Questions("14.", "Which one of the following is the scalar (dot) product of the vectors (2, -4, 6) and (-2, -1, 0)\n", 0, 0, 0, 0, 0, "-8", "0", "6", "8", "", "b", "maths1314e", 1, True));
question_list.append(Questions("15.", "The inverse of the function y= 3x - 5 is equal to ", 0, 0, 0, 0, 0, "y = (x+3)/5", "y = (x+5)/3", "y = -5x + 3", "y = (x-5)/3", "", "b", "maths1315e", 1, True));
question_list.append(Questions("16.", "", "maths1316q", 0, 0, 0, 0, "R/{0}", "R/{0, 1}", "R/{0, -1}", "R/{0, 1, -1}", "", "c", "maths1316e", 1, True));
question_list.append(Questions("17.", "", "maths1317q", 0, 0, 0, 0, "y = 0 is its horizontal asymptote. ", "x = 1 is its vertical asymptote. ", "It is increasing on (∞,1). ", "It is decreasing on (1, ∞).", "", "d", "maths1317e", 1, True));
question_list.append(Questions("18.", "The equation of a line is given by 3x - 2y + 6 = 0. Then which of the following is true about the line? \n", 0, 0, 0, 0, 0, "Its slope is 3/2. ", "Its y-intercept is -3. ", "Its x-intercept is 2. ", "(2,5) lies on the line.", "", "a", "maths1318e", 1, True));
question_list.append(Questions("19.", "Which one of the following is the standard form of the equation of the parabola with vertex (4,6) and focus (-8,6)?\n", 0, "maths1319a", "maths1319b", "maths1319c", "maths1319d", "", "", "", "", "", "c", "maths1319e", 1, True));
question_list.append(Questions("20.", "", "maths1320q", 0, 0, 0, 0, "Its vertices are at (-2,0) and (2,0).", "Its foci are at (-5,0) and (5,0). ", "An asymptote to the hyperbola is y=2x. ", "Its center is at (2,1)", "", "a", "maths1320e", 1, True));
question_list.append(Questions("21.", "Two statements p and q are given by p:22/7 is an irrational number. q= the sum of two odd integers is odd. Then which of the following has a truth value T?", 0, "maths1321a", "maths1321b", "maths1321c", "maths1321d", "", "", "", "", "", "a", "maths1321e", 1, True));
question_list.append(Questions("22.", "Which one of the following is the contrapositive of the statement: 'If 21 is a prime number, then 4 is an odd number'\n", 0, 0, 0, 0, 0, "If 4 is an odd number, then 21 is a prime number.", "If 4 is an odd number, then 21 is not a prime number.", "If 21 is not a prime number, then 4 is an even number. ", "If 4 is not an odd number, then 21 is not a prime number.", "", "d", "maths1322e", 1, True));
question_list.append(Questions("23.", "", "maths1323q", 0, 0, 0, 0, "5", "6.5", "7", "7.5", "", "c", "maths1323e", 1, True));
question_list.append(Questions("24.", "In a certain health center there are 3 doctors, 8 nurses and 2 physicians. In how many ways one can form a group of 5 members consisting of 1 doctor, 3 nurses and 1 physician? \n", 0, 0, 0, 0, 0, "112", "168", "330", "336", "", "d", "maths1324e", 1, True));
question_list.append(Questions("25.", "Which one of the following forms represents an exhaustive set of events if a die is thrown once?\n", 0, 0, 0, 0, 0, "{1, 2, 3}, {4, 5}, {6}", "{1, 2}, {4}, {4, 5, 6}", "{1, 2, 3}, {3, 4}, {6}", "{1, 2}, {2}, {4, 5}, {5, 6}", "Exhaustive events is a set of events where at least one of them must occur whenever the experiment is performed. \nThe exhaustive events of a die thrown once is {1,2,3}, {4,5}, {6} ", "a", 0, 1, True));
question_list.append(Questions("26.", "A bag contains 2 red, 3 yellow and 5 green balls. One ball is drawn at random. What is the probability that the drawn ball is NOT yellow? \n", 0, 0, 0, 0, 0, "1/5 ", "3/10 ", "7/10 ", "4/5", "Given \n\n2 red, 3 yellow and 5 green balls \n\nSolution \n\nP(red ball) = 2/10 \nP(green ball) = 5/10 \nP(yellow ball) = 3/10 \nP(not yellow) = 1 — P(yellow) \n= 1 - 3/10 \n= 7/10 ", "c", 0, 1, True));
question_list.append(Questions("27.", "", "maths1327q", "maths1327a", "maths1327b", "maths1327c", "maths1327d", "", "", "", "", "", "d", "maths1327e", 1, True));
question_list.append(Questions("28.", "Which one of the following is NOT true about the determinant of a given square matrix A? \n", 0, 0, 0, 0, 0, "If A has identical rows, then its determinant is zero. ", "If A contains a row of zeros, then its determinant is zero. ", "Interchanging two rows of A gives the same determinant. ", "The determinant of A is equal to the determinant of its transpose.", "", "c", "maths1328e", 1, True));
question_list.append(Questions("29.", "", "maths1329q", "maths1329a", "maths1329b", "maths1329c", "maths1329d", "", "", "", "", "", "b", "maths1329e", 1, True));
question_list.append(Questions("30.", "", "maths1330q", 0, 0, 0, 0, "If a = -2, then the system has a unique solution. ", "If a > -2, then the system has a unique solution. ", "If a > 2, then the system has infinitely many solutions. ", "If a = 2, then the system has no solution.", "", "b", "maths1330e", 1, True));
question_list.append(Questions("31.", "What is the magnitude of the vector whose initial point is at (1, -3) and terminal point is at (4, 1)? \n", 0, 0, 0, 0, 0, "6", "5", "4", "1", "", "b", "maths1331e", 1, True));
question_list.append(Questions("32.", "Let T be a translation that takes the origin into (2,3). Then which of the following is true about the translation T?\n", 0, "maths1332a", "maths1332b", "maths1332c", "maths1332d", "", "", "", "", "", "a", "maths1332e", 1, True));
question_list.append(Questions("33.", "", "maths1333q", 0, 0, 0, 0, "f(x) = secx ", "f(x) = tanx ", "f(x) = cotx ", "f(x) = cscx", "", "c", "maths1333e", 1, True));
question_list.append(Questions("34.", "Which of the following is true?", 0, "maths1334a", "maths1334b", "maths1334c", "maths1334d", "", "", "", "", "", "b", "maths1334e", 1, True));
question_list.append(Questions("35.", "Which one of the following is the fourth term of the sequence {cos(nπ/2)}? \n", 0, 0, 0, 0, 0, "-1", "0", "0.5", "1", "", "d", "maths1335e", 1, True));
question_list.append(Questions("36.", "Which of the following is a geometric sequence? \n", 0, 0, 0, 0, 0, "0.1, 0.01, 0.0011, 0.000111, ... ", "1, 1.5, 2.5, 3.5, ... ", "0.1, 0.11, 0.12, 0.13, ...", "8, -4, 2, -1, …", "8, -4, 2, -1, … Is a geometric sequence with first term 8 and common ratio -1/2 ", "d", 0, 1, True));
question_list.append(Questions("37.", "A factory that produces electric cable had sales Birr 1,000,000 the first day. During each successive days the sales increased by Birr 10,000 every day. What is the total sales of the factory in the first 10 days? \n", 0, 0, 0, 0, 0, "Birr 1,090,000", "Birr 10,000,000", "Birr 10,450,000", "Birr 10,900,000", "", "c", "maths1337e", 1, True));
question_list.append(Questions("38.", "", "maths1338q", 0, 0, 0, 0, "0", "1", 2, 3, "", "d", "maths1338e", 1, True));
question_list.append(Questions("39.", "Which one of the following sequences is a null sequence? \n", 0, 0, 0, 0, 0, "{1-1/n}", "{nsin(1/n)} ", "{cosn/n} ", "{n/n+1}", "", "c", "maths1339e", 1, True));
question_list.append(Questions("40.", "", "maths1340q", "maths1340a", "maths1340b", "maths1340c", "maths1340d", "", "", "", "", "", "d", "maths1340e", 1, True));
question_list.append(Questions("41.", "", "maths1341q", 0, 0, 0, 0, "-3", "-1", "0", "1", "", "a", "maths1341e", 1, True));
question_list.append(Questions("42.", "Which of the following is the same as the derivative of a function f at a point P, where P is on the graph of f? \n", 0, 0, 0, 0, 0, "The slope of a secant line through P. ", "The continuity of the function at P. ", "The graph of f has no jump at P. ", "The slope of the tangent line through P.", "", "d", "maths1342e", 1, True));
question_list.append(Questions("43.", "", "maths1343q", 0, 0, 0, 0, "-3", "-1", "1", 3, "", "d", "maths1343e", 1, True));
question_list.append(Questions("44.", "", "maths1344q", "maths1344a", "maths1344b", "maths1344c", "maths1344d", "", "", "", "", "", "d", "maths1344e", 1, True));
question_list.append(Questions("45.", "Which of the following is true about the zero of a function? \n", 0, 0, 0, 0, 0, "It is the x-intercept of the function. ", "It is the y-intercept of the function. ", "It is the critical point of the function. ", "It is the concavity point of the function.", "The zero of a function is the x-intercept of the function. i.e., f(x)= 0 ", "a", 0, 1, True));
question_list.append(Questions("46.", "", "maths1346q", 0, 0, 0, 0, "Its critical numbers are 0, 2, 3 and its maximum value is 0. ", "Its critical numbers are 0 and 2 and its maximum value is 15. ", "Its critical numbers are 0 and 2 and its maximum value is -4. ", "It has critical numbers at 0 and 2 and its maximum value is 0.", "", "d", "maths1346e", 1, True));
question_list.append(Questions("47.", "", "maths1347q", 0, 0, 0, 0, "-3/2", "1", "3/2", 2, "", "c", "maths1347e", 1, True));
question_list.append(Questions("48.", "What are the length L and width W of a rectangle with perimeter 10,000m that maximizes the area? \n", 0, 0, 0, 0, 0, "L = 2,500m and W = 2,500m", "L = 2,500m and W = 3,000m", "L = 3,000m and W = 2,500m", "L = 5,000m and W = 5,000m", "", "a", "maths1348e", 1, True));
question_list.append(Questions("49.", "If the radius r of a sphere is increasing at the rate of 2cm/min, then the rate of change of the volume of when r=1cm is\n", 0, "maths1349a", "maths1349b", "maths1349c", "maths1349d", "", "", "", "", "", "c", "maths1349e", 1, True));
question_list.append(Questions("50.", "", "maths1350q", "maths1350a", "maths1350b", "maths1350c", "maths1350d", "", "", "", "", "", "d", "maths1350e", 1, True));
question_list.append(Questions("51.", "", "maths1351q", 0, 0, 0, 0, "2/3", "22/3", "8", "26/3", "", "b", "maths1351e", 1, True));
question_list.append(Questions("52.", "", "maths1352q", 0, 0, 0, 0, "-4", 2, "4", "16", "", "a", "maths1352e", 1, True));
question_list.append(Questions("53.", "Which of the following statements has a truth value T?\n", 0, "maths1353a", "maths1353b", "maths1353c", "maths1353d", "", "", "", "", "", "b", "maths1353e", 1, True));
question_list.append(Questions("54.", "", "maths1354q", 0, 0, 0, 0, "4", "5", "√20", "√21", "", "d", "maths1354e", 1, True));
question_list.append(Questions("55.", "", "maths1355q", 0, 0, 0, 0, "0", "6", "500", "576", "", "a", "maths1355e", 1, True));
question_list.append(Questions("56.", "Which of the following is true about the graph of y = -4cos(2x/3)?", 0, 0, 0, 0, 0, "Its amplitude is -4 ", "Its period is 3π ", "The graph completes one cycle on the interval [0, 2π /3] ", "The graph completes one cycle on the interval [0, 3π /2]", "", "b", "maths1356e", 1, True));
question_list.append(Questions("57.", "", "maths1357q", 0, 0, 0, 0, "4m", "8m", "12m", "14m", "", "c", "maths1357e", 1, True));
question_list.append(Questions("58.", "Which of the following series is convergent?", 0, "maths1358a", "maths1358b", "maths1358c", "maths1358d", "", "", "", "", "", "b", "maths1358e", 1, True));
question_list.append(Questions("59.", "Let f be a function defined on a closed bounded interval [a,b]. Which of the following describes that f is continuous on [a,b]? \n", 0, 0, 0, 0, 0, "f is continuous at each point in (a,b) and at both a and b. ", "f is continuous on (a,b), f is continuous from the right at a and from the left at b. ", "f is continuous on (a,b), f is continuous from the left at a and from the left b. ", "f is continuous on (a,b), f is continuous from the left at a and from the right at b.", "If f is continuous on [a, b], then \n•f is continuous on (a, b) \n• f is continuous from the right at a \n• f is continuous from the left at b \n", "b", 0, 1, True));
question_list.append(Questions("60.", "", "maths1360q", "maths1360a", "maths1360b", "maths1360c", "maths1360d", "2π", 2, "2π+1", "2π-1", "", "c", "maths1360e", 1, True));
question_list.append(Questions("61.", "If f'(1) = 4, f(1) = 3 and g'(3) = 5, then (gof)'(l) is equal to \n", 0, 0, 0, 0, 0, 3, "5", "15", "20", "", "d", "maths1361e", 1, True));
question_list.append(Questions("62.", "Which of the following is true where c is at constant?\n", 0, "maths1362a", "maths1362b", "maths1362c", "maths1362d", "", "", "", "", "", "b", "maths1362e", 1, True));
question_list.append(Questions("63.", "", "maths1363q", "maths1363a", "maths1363b", "maths1363c", "maths1363d", "", "", "", "", "", "a", "maths1363e", 1, True));
question_list.append(Questions("64.", "Which of the following arguments is valid?", 0, "maths1364a", "maths1364b", "maths1364c", "maths1364d", "", "", "", "", "", "a", "maths1364e", 1, True));
question_list.append(Questions("65.", "", "maths1365q", 0, 0, 0, 0, "Proof by the principle of mathematical induction. ", "Proof by counter example. ", "Proof by indirect proof. ", "Proof by contradiction.", "Proof by the principle of mathematical induction. ", "a", 0, 1, True));

# subject_slug = "12phy2013"
# question_list.append(Questions("1.", "The second law of thermodynamics states that ", 0, 0, 0, 0, 0, "no process is possible in which there is an overall increase in the entropy of the universe.", "no process is possible in which there is an overall decrease in the entropy of the universe.", "two bodies that are separately in thermal equilibrium with a third body must be in thermal equilibrium with each other.", "the increase in the internal energy of a system is equal to the sum of the energy entering the system through heating, and work done on the system. ", "The second law of thermodynamics states that; \nNo process is possible in which there is an overall decrease in the entropy of the universe. Or \nComplete conversion of heat into useful work is not possible. Or \nSpontaneous flow of heat from a colder body to a hotter body is impossible. ", "b", 0, 1, True));
# question_list.append(Questions("2.", "A mass-spring system set to oscillate in a simple harmonic motion over friction less horizontal surface. The amplitude of this oscillation is 20 cm. A second mass-spring system with the same spring constant is set to oscillate in the same way but with amplitude Of 10 cm. The energy of the ", 0, 0, 0, 0, 0, "second mass-spring system has half of the first one. ", "first mass-spring system has twice the second one.", "second mass-spring system has the square of the first one. ", "first mass-spring system has four times the second one. ", "", "d", "phy1302e", 1, True));
# question_list.append(Questions("3.", "A string vibrates with speed of in its frequency of 880Hz. What is the length of the string? ", 0, 0, 0, 0, 0, "31.3 cm ", "50.0 cm ", "12.5 cm ", "25.0 cm ", "", "d", "phy1303e", 1, True));
# question_list.append(Questions("4.", "An interference patterns observed after a monochromatic beam of light passes through a single slit and a double slit. Which one of the following is Correct about the width of the central maxima and the first order maxima in single slit and double slit? ", 0, 0, 0, 0, 0, "The width Of the central maxima has twice the width of the first order maxima in a single slit interference while it has equal width in double slit interference. ", "The width of the central maxima and first order maxima has equal width in both cases. ", "The width of the central maxima has twice the width of the first order maxima in both cases. ", "The width Of the central maxima has equal with the width Of the first order maxima in a single slit interference while it has twice the width of the order maxima in double slit interference. ", "", "a", 0, 1, True));
# question_list.append(Questions("5.", "A light wave of wavelength 590nm pass through a narrow double slit of 0.2mm slit separation. An interference pattern is formed on a screen at a distance of 1.5m. \nWhat is the distance between the consecutive bright fringes on the screen? ", 0, 0, 0, 0, 0, "44.3 mm ", "0.43 mm ", "4.43 mm ", "1.97 mm ", "", "c", "phy1305e", 1, True));
# question_list.append(Questions("6.", "According to Gauss's law the net electric flux through any hypothetical closed surface is proportional to the enclosed; ", 0, 0, 0, 0, 0, "Electric charge. ", "Electric current. ", "Potential difference. ", "Electric field. ", "", "a", "phy1306e", 1, True));
# question_list.append(Questions("7.", "When a dielectric material placed between tv parallel metal plates in the presence of electric fields they enable the plates to store ", 0, 0, 0, 0, 0, "much more charge at different potential difference.", "much more charge at the same potential difference. ", "the same charge at the same potential difference. ", "much less charge at difference potential difference. ", "", "b", 0, 1, True));
# question_list.append(Questions("8.", "", "phy1308q", "phy1308a", "phy1308b", "phy1308c", "phy1308d", "", "", "", "", "", "d", "phy1308e", 1, True));
# question_list.append(Questions("9.", "A uniform conductor of length L and cross-sectional area A carries a current I when a potential difference V is applied across its ends. If the number free electrons per unit volume Of the conductor is n, and the electron charge is e, then the drift velocity Of the electrons in the conductor is ", 0, 0, 0, 0, 0, "V = I/neL ", "V = I/neLA ", "V = I/neA ", "V = I/eAL ", "The total charge is obtained by : \nQ = nVe , v = AL = VoIume \nQ = nALe, L = vt \nQ = nAvte , \nv = Q/(nAte) but Q/T=I \nv = l/neA ", "c", 0, 1, True));
# question_list.append(Questions("10.", "Which one of the following statement is correct about, a bar on which a force acts at one end and pivoted at the other? ", 0, 0, 0, 0, 0, "The force is collinear with the angular velocity. ", "The force is coplanar with the torque it produces. ", "The force, angular velocity and the torque are coplanar. ", "The force is parallel to the angular acceleration produced. ", "T = r x F", "b", 0, 1, True));
# question_list.append(Questions("11.", "The necessary condition for an object to be in rotational equilibrium is ", 0, 0, 0, 0, 0, "the sum of clockwise torques equals to the sum of counter clock-wise torques. ", "the net force exerting on the object must be zero. ", "the net torque action on the object is different from zero. ", "the net moment Of all forces should be non-zero. ", "If clockwise torque sum equals counter clockwise torque sum,then second condition or the rotational equilibrium is satisfied. ", "a", 0, 1, True));
# question_list.append(Questions("12.", "An aluminum wire of initial length 2.0m where increased by 2.0 cmin its length being on application Of a force Of 9.0N. \nWhat is the strain energy Of the material? ", 0, "phy1312a", "phy1312b", "phy1312c", "phy1312d", "", "", "", "", "", "b", "phy1312e", 1, True));
# question_list.append(Questions("13.", "", "phy1313q", 0, 0, 0, 0, "1.6 mm ", "3.2 mm ", "0.16 mm ", "0.32 mm ", "", "d", "phy1313e", 1, True));
# question_list.append(Questions("14.", "Suppose a stream of fluid flows past a solid object, which one of the following does NOT affect the linear flow of the fluid. ", 0, 0, 0, 0, 0, "The speed Of the solid object ", "The shape of the solid object ", "The density of the solid object ", "Viscosity of the fluid ", "", "c", 0, 1, True));
# question_list.append(Questions("15.", "Water enters a tube of non-uniform diameter. The speed of the force at the entry of area A1 is 12m/s and the speed becomes 4m/s at the exit opening Of area A2. Which one is correct about the ratio of A1/A2? ", 0, 0, 0, 0, 0, "1/3 ", "3", "4", "1/4", "From continuity equation: \nA1V1 = A2V2\n12A1 = 4A2\nA1/A2 = 4/12 = 1/3", "a", 0, 1, True));
# question_list.append(Questions("16.", "The particular temperature and pressure at which the solid, liquid, and gaseous phases of a given substance are all at equilibrium with another is known as: ", 0, 0, 0, 0, 0, "Phase change. ", "Critical point. ", "Triple point. ", "Heat capacity. ", "", "c", 0, 1, True));
# question_list.append(Questions("17.", "Most solids expand upon heating, which one of the following statements correctly describe the phenomena? ", 0, 0, 0, 0, 0, "Increase in temperature decreases the vibrational kinetic energy and amplitude of the atoms constituting the solid. ", "Increase in temperature increases the vibrational kinetic energy and amplitude of the atoms constituting the solid. ", "Increase in temperature increases the vibrational kinetic energy and decreases the amplitude of the atoms constituting the solid. ", "Increase in temperature decreases the vibrational kinetic energy and increases the amplitude of the atoms constituting the solid. ", "", "b", 0, 1, True));
# question_list.append(Questions("18.", "If 25J is taken away by heat from a system, and the system does 20J of work, what is the change in internal energy of the system? ", 0, 0, 0, 0, 0, "-5.0 J", "5.0 J ", "-45.0 J ", "45.0 J ", "", "c", "phy1318e", 1, True));
# question_list.append(Questions("19.", "A sample mixture of gas contains 72% of hydrogen and 28% Of Helium. What is the partial pressure of helium at an atmospheric pressure of 76cm of mercury (Hg)? ", 0, 0, 0, 0, 0, "21.8 cm of Hg ", "54.72 cm of Hg ", "76.0 cm of Hg ", "33.44 cm of Hg", "From Dalton's partial pressure: \nP1 = P(n1/ (n1 + n2)) = 76 (28/ (28 + 72)) = 21.8 cmHg", "a", 0, 1, True));
# question_list.append(Questions("20.", "Kirchhoff's junction rule state that ", 0, 0, 0, 0, 0, "the same of the voltage drop across any closed loop equals the sum Of electromotive force. ", "charge entering the junction equals the charge leaving that junction at a particular time. ", "the potential drop at a given junction equals the electromotive force at that particular point. ", "current traversing any closed loop at particular time is zero. ", "", "b", 0, 1, True));
# question_list.append(Questions("21.", "Which one of the following statement is NOT correct about the magnetic properties of matter? ", 0, 0, 0, 0, 0, "The unpaired electrons in paramagnetic substance which will tend to align themselves in the same direction as the applied magnetic field. ", "The unpaired electrons in ferromagnetic materials will align with the applied magnetic field and parallel to each other. ", "The unpaired electrons in diamagnetic materials will align with the applied magnetic field and parallel to each other. ", "There is a tendency to oppose the applied magnetic field in a diamagnetic substance.", "", "c", 0, 1, True));
# question_list.append(Questions("22.", "Suppose a conductor of length l carrying a current I placed in a uniform magnetic field of magnitude B. When the conductor is making an angle with that of the magnetic field then force experienced by the conductor due to the magnetic field is given by ", 0, 0, 0, 0, 0, "F = l (l x B)", "F = lB (l tanθ)", "F = lB (l cosθ)", "F = l (B x l)", "", "a", 0, 1, True));
# question_list.append(Questions("23.", "Which one of the following statement is correct about tangent galvanometer? ", 0, 0, 0, 0, 0, "It is a device used to measure the electric current in terms of the electric field it produces. ", "The current is inversely proportional to the tangent of the angle of the needle's deflection. ", "It consists of a coil of insulated copper wire on a circular magnetic frame. ", "The current through a coil of the wire generates a magnetic field at the center of coil. ", "", "b", 0, 1, True));
# question_list.append(Questions("24.", "", "phy1324q", 0, 0, 0, 0, "The field strength is directly proportional to the distance from the conductor. ", "The magnetic field encircles conductor. ", "Reversing the current direction will reverse the direction of the magnetic field. ", "Doubling the current through the conductor doubles the field strength. ", "From Ampere's law and the right hand rule", "a", 0, 1, True));
# question_list.append(Questions("25.", "", "phy1325q", 0, 0, 0, 0, "1.8 mV ", "18 mV ", "9.0 mV ", "3.2 mv ", "", "a", "phy1325e", 1, True));
# question_list.append(Questions("26.", "A 15.0 mH inductor is used to induce an electromotive force of 5.0 mV, What is the rate change Of the induced current?", 0, 0, 0, 0, 0, "3.3 A/s ", "0.33 A/s ", "0.3 A/s ", "3.0 A/s ", "", "b", "phy1326e", 1, True));
# question_list.append(Questions("27.", "A coil and a permanent magnet are set in relative motion. Which one of the following statement is NOT correct about induced electromotive force? ", 0, 0, 0, 0, 0, "The direction in which the coil moves relative to the magnetic field does not have any effect on the induced electromotive force.", "The magnitude of the induced electromotive force is directly proportional to the relative velocity between the two. ", "Moving a magnet relative to the coil and the coil relative to the magnet with equal speed will produce the same electromotive force.", "Coil with larger number of turns produce greater induced electromotive forces. ", "From Faraday's and Lenz's law", "a", 0, 1, True));
# question_list.append(Questions("28.", "What is the advantage of using alternating current in transmission of electric energy? ", 0, 0, 0, 0, 0, "It uses very high current in the transmission line. ", "It completely avoids energy loss due to heating.", "It enables a transformer to increase or decrease the voltage as required. ", "It enables to reach the consumers at very high voltage. ", "", "c", 0, 1, True));
# question_list.append(Questions("29.", "Capacitive reactance is defined as ", 0, 0, 0, 0, 0, "The equivalent quantity to resistance when we are talking about resistors. ", "The equivalent quantity to resistance when we are talking about inductors. ", "The equivalent quantity to impedance in RLC circuit. ", "The equivalent quantity to resistance when we are talking about capacitors. ", "", "d", 0, 1, True));
# question_list.append(Questions("30.", "Which one of the following is NOT correct about the concept and units of coefficient or friction? ", 0, 0, 0, 0, 0, "The coefficient of friction is always less or equal to unity (1). ", "Coefficient of static friction has no unit. ", "Coefficient of static friction is less than its value of kinetic friction. ", "Coefficient of friction is the ratio of frictional force to normal force. ", "", "c", 0, 1, True));
# question_list.append(Questions("31.", "A car is travelling at constant velocity along a straight line. Which statement is correct? ", 0, 0, 0, 0, 0, "The acceleration Of the car is in opposite direction. ", "The net force on the car is different from zero.", "The displacement of the car is in opposite direction.", "The displacement of the car increase linearly with time. ", "", "d", 0, 1, True));
# question_list.append(Questions("32.", "Which one of the following statements is correct about the impulse on an object? ", 0, 0, 0, 0, 0, "Impulse is the rate of change in momentum due to external force exerted on an object for a very short period of time.", "Impulse is the change in momentum when a force is exerted on an object for a very short period of time. ", "The area under the curve of momentum versus time graph is the impulse on an object. ", "The impulse on an object is changed when the net force acting on the object is zero. ", "", "b", "phy1332e", 1, True));
# question_list.append(Questions("33.", "Consider collisions, that occurred between two trollies having the same mass: moving the same speed, and in opposite directions, \nCollision 1:- after collision the two trollies bounce back with the same speed. \nCollision 2:- after collision the two trollies back with the same coupler ", 0, 0, 0, 0, 0, "Collision 1 is inelastic is inelastic and collision 2 elastic.", "Both collisions are inelastic. ", "Collision 1 is elastic and collision 2 is inelastic. ", "Both collisions are elastic. ", "", "c", 0, 1, True));
# question_list.append(Questions("34.", "Suppose that you are given a mass attached to a spring and oscillates up and down. This mass-spring system has maximum gravitational potential energy (GPE), elastic potential energy (EPE) and kinetic energy (KE) at the ", 0, 0, 0, 0, 0, "top, bottom and middle respectively. ", "bottom, middle and top respectively. ", "middle, bottom and top respectively. ", "middle, top and bottom respectively. ", "", "a", 0, 1, True));
# question_list.append(Questions("35.", "", "phy1335q", 0, 0, 0, 0, "0.4 m ", "0.2 m ", "2.5 m ", "0.1 m ", "", "b", "phy1335e", 1, True));
# question_list.append(Questions("36.", "A 5.0 kg stone is dropped from a top of 30.0 m building. At a height of 10.0m above the ground, 60% of its initial potential energy is converted to kinetic energy. \nWhich one of the following statements is correct about the transformation of energy for the stone? ", 0, 0, 0, 0, 0, "The remaining 40% of the energy is still available as gravitational potential energy. ", "60% Of its original potential energy is converted to heat energy dues to air resistance. ", "6.7% of gravitational potential energy is dissipated due to air resistance. ", "The sum of its potential energy and kinetic energy is the same at every point during its fall. ", "When the stone is at a height of 30m, its potential energy is: \nPE1 = mgh1 = 5(10)(30) = 1500J \nAnd, when the stone is at 10m from the ground, \nPE2 = mgh2 = 5(10)(10) = 500J \nIn percent: PE2/PE1 = (500/1500) 100% = 33.3%, hence 6.7% is waste. ", "c", 0, 1, True));
# question_list.append(Questions("37.", "", "phy1337q", 0, 0, 0, 0, "7.0 k ", "24.0 k ", "-24.0 Nm k ", "-7.0 k", "", "a", "phy1337e", 1, True));
# question_list.append(Questions("38.", "A wheel starts rotating at 1.2 Hz and reaches 1.8 Hz. in 5 seconds. Calculate the angular displacement it covers within 5 seconds. ", 0, 0, 0, 0, 0, "15 π rad ", "30 π rad ", "3 π rad ", "10 π rad ", "", "a", "phy1338e", 1, True));
# question_list.append(Questions("39.", "If you are given the following physical quantities in angular motion:torque (r), Linear momentum(p), moment of inertia (l), angular speed (w) and angular acceleration (a). The angular momentum (L) is the ", 0, 0, 0, 0, 0, "ratio of linear momentum to moment of inertia. ", "product of moment of inertia and torque. ", "ratio of moment of inertia to angular acceleration. ", "product of moment of inertia and angular speed. ", "L = Iw = r(p)sinθ = r(m)vsinθ", "d", 0, 1, True));
# question_list.append(Questions("40.", "A student wants to measure the length and height of the school laboratory. There are vernier calipers, meter stick, micrometer screw gauge and meter tape measuring instruments in the laboratory \nWhich one of the following measuring instruments and unit is appropriate for the measurement? ", 0, 0, 0, 0, 0, "Meter stick and centimeter ", "Micrometer screw gauge and millimeter ", "Vernier calipers and millimeter ", "Meter tape and meter ", "", "d", 0, 1, True));
# question_list.append(Questions("41.", "", "phy1341q", 0, 0, 0, 0, "A", "B", "C", "D", "", "b", 0, 1, True));
# question_list.append(Questions("42.", "", "phy1342q", 0, 0, 0, 0, "A", "B", "C", "D", "North-East means North of East", "d", 0, 1, True));
# question_list.append(Questions("43.", "", "phy1343q", 0, 0, 0, 0, "A", "B", "C", "D", "Join the vectors head to tail and the resultant will be from the tail of first vectors to the head of the second vector. ", "c", 0, 1, True));
# question_list.append(Questions("44.", "", "phy1344q", 0, 0, 0, 0, "A", "B", "C", "D", "Two vectors are collinear if their cross product is zero. ", "d", 0, 1, True));
# question_list.append(Questions("45.", "Instantaneous velocity is different from average velocity in that; instantaneous velocity is ", 0, 0, 0, 0, 0, "the average velocity during the time of acceleration. ", "the total displacement to the time taken. ", "in opposite direction to the displacement of the moving object. ", "the velocity at a particular instant of time. ", "", "d", 0, 1, True));
# question_list.append(Questions("46.", "A car travelling at 20m/s starts to speedup. After 5 minutes its speed is 144m/s. What is the acceleration of the car? ", 0, "phy1346a", "phy1346b", "phy1346c", "phy1346d", "", "", "", "", "", "c", "phy1346e", 1, True));
# question_list.append(Questions("47.", "A bullet Of 200g mass fired from a 30.0 m high building, horizontally, At the same time a bullet Of the same mass fired vertically down from the same height, What can be concluded about the motion of the two bullets? ", 0, 0, 0, 0, 0, "A bullet fired horizontally takes more time to strike the ground. ", "Both bullets strike the ground at the same time. ", "Both bullets move with the same horizontal velocity. ", "A bullet fired vertically takes more time to strike the ground ", "", "b", 0, 1, True));
# question_list.append(Questions("48.", "A bird flies at speed of 10m/s south relative to the Earth. A wind blows at speed of 4m/s to east relative to the Earth. What is the speed of the bird relative to the wind? ", 0, 0, 0, 0, 0, "10.8m/s in the direction of South-West ", "6m/s in the direction Of South-East ", "10.8m/s in the direction of North-West ", "6m/s in the direction Of North-East ", "", "a", "phy1348e", 1, True));
# question_list.append(Questions("49.", "Dynamics is a branch of mechanics concerned with the motion of an object ", 0, 0, 0, 0, 0, "whose velocity is constant. ", "without its causes. ", "under the cation of balanced forces. ", "under the cation of forces. ", "", "d", 0, 1, True));


prepared_data = prepare_data(question_list, subject_slug)
print("finished")